
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.8.9-300.fc40.x86_64 - x86_64
...
